[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "centre"
version = "0.9.0"
description = "Your Window Position Manager"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Jack Scott", email = "cloner.bl12@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "keyboard>=0.13.5",
    "psutil>=7.2.2",
    "pyautogui>=0.9.54",
    "pydantic>=2.13.4",
    "pygetwindow>=0.0.9",
    "pywin32>=312",
    "watchdog>=6.0.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: Microsoft :: Windows",
    "Environment :: Win32 (MS Windows)",
]

[project.urls]
Homepage = "https://github.com/JackScott7/centre"
Repository = "https://github.com/JackScott7/centre"
Issues = "https://github.com/JackScott7/centre/issues"

[project.scripts]
centre = "centre.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
centre = ["sounds/*.wav"]
